Excluded Demo\CPPDemo\RTMP from x86 build config due to below errors: Error C1001 Internal compiler error. RTMP ..\demo\cppdemo\3rdparty\zlib\crc32.c Error LNK1000 Internal error during IMAGE::BuildImage RTMP ..\Demo\CPPDemo\RTMP\LINK